### ISSUE TITLE
No ApiProvider available in react context

### ISSUE THREAD

**Issue by adusumillipraveen** [RoadieHQ/backstage-plugin-github-pull-requests#13] opened 2020-10-05 09:23 UTC
I have tried to add this to our instance of backstage in local and getting this error :

```
index.esm.js?9424:formatted:112 Uncaught Error: No ApiProvider available in react context
    at useApiHolder (index.esm.js?9424:formatted:112)
    at useApi (index.esm.js?9424:formatted:119)
    at usePullRequestsStatistics (index.esm.js?8287:274)
    at PullRequestsStats (index.esm.js?8287:317)
```

Does it need any additional config to be added or does it expect any other plugin to be installed already ?

**Comment by iain-b** [comment] 2020-10-05 09:38
We've seen this issue before where there's a version mismatch between the backstage app and the plugin - specifically between alpha22 and alpha23. We've updated the plugin to be compatible with alpha23 as of version 0.4.3.
What version of backstage are you using? And what version of the plugin?
Also we're on discord if you prefer https://discord.gg/55NVwR

**Comment by iain-b** [comment] 2020-10-05 11:10
@adusumillipraveen If you're using alpha22 try using pinng to version 0.4.2 or below of the plugin. If you're on alpha23 (latest) then try upgrading to 0.4.3. If you're still having issues do reach out to us with more info so we can get to the bottom of the problem.

**Comment by adusumillipraveen** [comment] 2020-10-05 12:14
Hey, I was using an old version of backstage app. Let me try to upgrade it and see how it goes.  will keep you posted

**Comment by dtuite** [comment] 2020-10-05 13:15
Thanks @adusumillipraveen. I'm going to close this one in the meantime but let us know if the problem is not fixed please and we will reopen.

**Comment by adusumillipraveen** [comment] 2020-10-05 13:20
That took me to the next step, having an issue with Github Auth setup/ redirection. But, i should be able to figure it out / reach to someone for help on discord.  Thanks again for your prompt response

**Comment by dtuite** [comment] 2020-10-05 13:36
Great stuff @adusumillipraveen. I actually wrote a short guide to GitHub auth on Backstage. You can find it here: https://roadie.io/blog/github-auth-backstage/ It might help.

**Comment by dtuite** [comment] 2020-10-05 13:36
(For anyone wondering, I misclick re-opened the issue)

**Closed by dtuite** 2020-10-05 13:36 UTC

**Comment by adusumillipraveen** [comment] 2020-10-05 13:40
> Great stuff @adusumillipraveen. I actually wrote a short guide to GitHub auth on Backstage. You can find it here: https://roadie.io/blog/github-auth-backstage/ It might help.

Just got it working a couple of minutes before seeing this. But that's very helpful, thanks.
